// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * ═══════════════════════════════════════════════════════════════════════════
 *  IProphetCore — High Priest Interface
 *  Digital Tabernacle on Base L2
 * ═══════════════════════════════════════════════════════════════════════════
 *
 *  Interface for the ProphetCore "Proof-of-Listening" rewards contract.
 *  Tracks listening streaks, multipliers, and daily mint prophecies.
 * ═══════════════════════════════════════════════════════════════════════════
 */

interface IProphetCore {

    /* ═══════════ EVENTS ═══════════ */

    /// @notice Emitted when a disciple harvests tokens after verified listening
    event TokensHarvested(
        address indexed disciple,
        uint256 indexed songId,
        uint256 reward,
        uint256 streak
    );

    /// @notice Emitted when a daily prophecy is minted (Open Edition)
    event DailyProphecyMinted(
        address indexed disciple,
        uint256 indexed tokenId,
        uint256 indexed songId,
        uint256 timestamp
    );

    /// @notice Emitted when a daily prophecy is set by the Oracle
    event DailyProphecySet(
        uint256 indexed songId,
        uint256 expiresAt
    );

    /// @notice Emitted when a disciple's streak is updated
    event StreakUpdated(
        address indexed disciple,
        uint256 newStreak,
        uint256 multiplier
    );

    /* ═══════════ STRUCTS ═══════════ */

    struct DailyProphecyInfo {
        uint256 songId;
        uint256 expiresAt;
        uint256 totalMinted;
        string  metadataURI;
    }

    struct DiscipleInfo {
        uint256 currentStreak;
        uint256 lastListenTimestamp;
        uint256 totalHarvested;
        uint256 multiplier;
    }

    /* ═══════════ CORE FUNCTIONS ═══════════ */

    /// @notice Harvest tokens after Proof-of-Listening verification
    /// @param songId   The on-chain song identifier
    /// @param proofHash A keccak256 proof generated by the PoL middleware
    function harvestTokens(uint256 songId, bytes32 proofHash) external;

    /// @notice Mint the current daily prophecy (Open Edition, 24h window)
    /// @param songId The song the prophecy is tied to
    /// @return tokenId The minted NFT token ID
    function mintDailyProphecy(uint256 songId) external payable returns (uint256 tokenId);

    /* ═══════════ VIEW FUNCTIONS ═══════════ */

    /// @notice Get a disciple's current listening streak (consecutive days)
    function currentStreak(address disciple) external view returns (uint256);

    /// @notice Get a disciple's last listen timestamp
    function lastListenTimestamp(address disciple) external view returns (uint256);

    /// @notice Get the streak multiplier for a disciple
    /// @dev    7-day streak = 2×, 14-day = 3×, 30-day = 5×
    function getStreakMultiplier(address disciple) external view returns (uint256);

    /// @notice Get info about the current daily prophecy
    function dailyProphecy() external view returns (
        uint256 songId,
        uint256 expiresAt,
        uint256 totalMinted
    );

    /// @notice Get full info about a disciple
    function getDiscipleInfo(address disciple) external view returns (DiscipleInfo memory);

    /* ═══════════ ORACLE FUNCTIONS ═══════════ */

    /// @notice Set the daily prophecy (Oracle / owner only)
    function setDailyProphecy(uint256 songId, string calldata metadataURI) external;

    /// @notice Update base reward amount
    function setBaseReward(uint256 amount) external;
}
